version: "3"

services:
  nginx:
    image: nginx:1.19.6
    ports:
      - 10080:10080
    volumes:
      - ${IMAGE_PATH}:/work/images
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf

  django:
    build:
      context: .
      dockerfile: conf/django/Dockerfile
    ports:
      - 8000:8000
    env_file:
      - .envs/.${ENVIRON}/.django
